#baseurl: /Po-Ting-lin

# Info about you
name: Brian's Blog
position: software Engineer
email: c1c4c5c6@gmail.com
company_name: Company Name
company_url: https://www.yourcompany.com
place_name: Taiwan

# Blog info
title: Brian's Blog
description: Blog
url: https://Po-Ting-lin.github.io/
main_github_io: true
long_description: >-
    Hi!  Welcome to my Blog.

# Social links
github_url: https://github.com/Po-Ting-lin
linkedin_url: https://www.linkedin.com/in/po-ting-lin-333aa1155
social:
  links:
    - https://www.linkedin.com/in/po-ting-lin-333aa1155
    - https://github.com/Po-Ting-lin

# Images + files
logo: assets/img/headshot.svg
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: light  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2D4F4F
  header_text: dbefdc
  header_link_hover: dbefdc
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: 000000
  tag: 2e6830
  tag_hover: 93cf95
  header_background: FFEBCD
  header_text: 2F4F4F
  header_link: 2F4F4F
  header_link_hover: 000000
  links: 000000
  links_visited: 000000
